#!/usr/bin/env python3
"""Print basic information about a keypoint Excel file."""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

DEFAULT_ROOT = Path('data/training_data')


def find_default_file(root: Path) -> Path:
    for path in sorted(root.rglob('*keypoints.xlsx')):
        return path
    raise FileNotFoundError(f"No Excel files found under {root}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'excel_path',
        nargs='?',
        type=Path,
        help='Path to an Excel file generated by the keypoint extractor',
    )
    parser.add_argument(
        '--root',
        type=Path,
        default=DEFAULT_ROOT,
        help='Root directory to search when no explicit file is provided',
    )
    args = parser.parse_args()

    excel_path = args.excel_path or find_default_file(args.root)
    print(f"Inspecting {excel_path}")

    xls = pd.ExcelFile(excel_path)
    print('Sheets:', ', '.join(xls.sheet_names))

    for sheet in xls.sheet_names:
        df = pd.read_excel(xls, sheet_name=sheet)
        print(f"\n--- {sheet} ---")
        print('Columns:', list(df.columns)[:5])
        print(df.head(3))
        print('Shape:', df.shape)


if __name__ == '__main__':
    main()
